CREATE TABLE STOCKS(
	STOCK_ID INT PRIMARY KEY auto_increment,
	STOCK_NAME VARCHAR(255) UNIQUE NOT NULL,
	STOCK_DESCRIPTION VARCHAR(255)
);

INSERT INTO STOCKS(STOCK_NAME) VALUES ('ANANT RAJ LIMITED');
INSERT INTO STOCKS(STOCK_NAME) VALUES ('ANSAL HOUSING & CONS');
INSERT INTO STOCKS(STOCK_NAME) VALUES ('ARICENT INFRA LTD.');
INSERT INTO STOCKS(STOCK_NAME) VALUES ('ARSS INFRA PROJECT LTD.');
INSERT INTO STOCKS(STOCK_NAME) VALUES ('ASHOK LAYLAND LIMITED');

CREATE TABLE STOCK_ENTRY(
	TRANSACTION_ID INT PRIMARY KEY auto_increment,
	TRANSACTION_DATE DATE,
	STOCK_ID INT,
	STOCKS_BUY_SELL VARCHAR(255),
	STOCKS_QUANTITY INT,
	PRICE_UNIT DOUBLE,
	/*BROKERAGE_UNIT DOUBLE,*/
	NET_TOTAL DOUBLE,
	STOCKS_REMAINING INT,
	STOCKS_LOSS DOUBLE DEFAULT 0,
	STOCKS_PROFIT DOUBLE DEFAULT 0
);

INSERT INTO STOCK_ENTRY(TRANSACTION_DATE,STOCK_ID,STOCKS_BUY_SELL,STOCKS_QUANTITY,PRICE_UNIT,NET_TOTAL)
VALUES ('2016-12-10',1,'BUY',100,10,1000);