-- SQL commands to create new user

.logon {DB_IP}/DBC,DBC;

CREATE USER "{NEWDB}" FROM "{PARENTDB}"
AS PERM = 524288000      
PASSWORD = "{NEWDB}"
SPOOL = 2147483648
TEMPORARY = 524288000
STARTUP = ''
NO FALLBACK
NO BEFORE JOURNAL
NO AFTER JOURNAL;

CREATE DATABASE "{NEWDB}_PUB" FROM "{NEWDB}"
AS PERM=52428800
SPOOL=52428800
TEMPORARY = 52428800
NO FALLBACK
NO BEFORE JOURNAL
NO AFTER JOURNAL;

CREATE DATABASE "{NEWDB}_CS" FROM "{NEWDB}"
AS PERM=52428800
SPOOL=52428800
TEMPORARY = 52428800
NO FALLBACK
NO BEFORE JOURNAL
NO AFTER JOURNAL;

--Grants Required for new DB

grant all on {NEWDB}_PUB to {NEWDB};
grant all on {NEWDB}_CS to {NEWDB};

grant all on {NEWDB} to {NEWDB} with grant option;
Grant select on dbc to {NEWDB};

GRANT UDTUSAGE ON SYSUDTLIB TO {NEWDB} WITH GRANT OPTION;
GRANT EXECUTE FUNCTION ON SYSSPATIAL TO {NEWDB};
GRANT SELECT ON SYSSPATIAL TO {NEWDB};
GRANT EXECUTE PROCEDURE ON SYSSPATIAL to {NEWDB};

GRANT EXECUTE PROCEDURE ON sqlj TO {NEWDB};
GRANT CREATE EXTERNAL PROCEDURE ON {NEWDB} TO {NEWDB} WITH GRANT OPTION;
GRANT EXECUTE PROCEDURE ON {NEWDB} TO {NEWDB};

--Grant all on test to {NEWDB};