.RUN FILE data/Login_Info.properties
 
.EXPORT REPORT FILE = data/DROPSTATEMENT.txt

.SET WIDTH 12000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;

SELECT DISTINCT
CASE WHEN  TABLEKIND= 'T'  THEN 'DROP TABLE   '||TRIM(TBLS.DATABASENAME)||'.'|| TRIM(TBLS.TABLENAME )||'  ;'  
WHEN TABLEKIND= 'V'  THEN 'DROP VIEW   '||TRIM(TBLS.DATABASENAME)||'.'|| TRIM(TBLS.TABLENAME )||'  ;'  
 WHEN TABLEKIND= 'M'  THEN 'DROP MACRO   '||TRIM(TBLS.DATABASENAME)||'.'|| TRIM(TBLS.TABLENAME )||'  ;'      
  WHEN TABLEKIND= 'P'  THEN 'DROP PROCEDURE   '||TRIM(TBLS.DATABASENAME)||'.'|| TRIM(TBLS.TABLENAME )||'  ;'        END     (TITLE '') 
FROM DBC.TABLESV TBLS
LEFT OUTER JOIN DBC.ALL_RI_CHILDREN RICHLD
ON TBLS.DATABASENAME =RICHLD.PARENTDB 
AND TBLS.TABLENAME =RICHLD.PARENTTABLE 

WHERE   TRIM(DATABASENAME) IN(sel databaseName from dbc.databases where ownername=user or databasename=user)
ORDER BY CASE WHEN RICHLD.PARENTTABLE IS NULL THEN 0 ELSE 1 END     ,TBLS.CREATETIMESTAMP;

.EXPORT RESET ;


.RUN FILE data/DROPSTATEMENT.txt


.QUIT
