.RUN FILE data/Login_Info.properties
 
.EXPORT REPORT FILE = data/DROPSTATEMENT.txt

.SET WIDTH 12000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;

SELECT 'DELETE USER '||TRIM(TBLS.DATABASENAME)|| ' ALL;'  (TITLE '') FROM DBC.DATABASES TBLS
WHERE	TRIM(DATABASENAME) IN ( SELECT DATABASENAME FROM DBC.DATABASES 
WHERE	OWNERNAME=user OR	DATABASENAME = user);

.EXPORT RESET ;

.RUN FILE data/DROPSTATEMENT.txt

.QUIT
