.RUN FILE data/Login_Info.properties


.EXPORT REPORT FILE = DATA/DROP_BKP.txt

.SET WIDTH 64000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;

SELECT 'DROP TABLE '||TRIM(DATABASENAME)||'.'||TRIM(SUBSTR(TABLENAME, 1, 1))||'BK'||TRIM(SUBSTR(TABLENAME, 4,LENGTH(TABLENAME)))||';'  (TITLE '') FROM  DBC.TABLESV
WHERE TABLEKIND ='T' AND TEMPORALPROPERTY <> 'N'
AND DATABASENAME IN (sel databaseName from dbc.databases where ownername=user or databasename=user)
AND TABLENAME IN ( SELECT TRIM(SUBSTR(TABLENAME, 1, 1))||'BK'||TRIM(SUBSTR(TABLENAME, 4,LENGTH(TABLENAME)))  FROM  DBC.TABLESV
WHERE TABLEKIND ='T' AND TEMPORALPROPERTY <> 'N'
AND DATABASENAME IN (SELECT DISTINCT(PHYSICAL_DB) FROM SYS_DB_MAP) ) 
ORDER BY CREATETIMESTAMP DESC;


.EXPORT RESET ;


 
.EXPORT REPORT FILE = DATA/RENAME_TAB.txt

.SET WIDTH 64000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;


SELECT 'RENAME TABLE '||TRIM(DATABASENAME)||'.'||TRIM(TABLENAME)||' TO '||TRIM(DATABASENAME)||'.'||TRIM(SUBSTR(TABLENAME, 1, 1))||'BK'||TRIM(SUBSTR(TABLENAME, 4,LENGTH(TABLENAME)))||';' (TITLE '') FROM  DBC.TABLESV
WHERE TABLEKIND ='T' AND TEMPORALPROPERTY <> 'N'
AND DATABASENAME IN (sel databaseName from dbc.databases where ownername=user or databasename=user)
ORDER BY CREATETIMESTAMP DESC;


.EXPORT RESET ;



.EXPORT REPORT FILE = DATA/INSERT_TAB.txt;

.SET WIDTH 64000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;

SELECT 'INSERT INTO  '||TRIM(DATABASENAME)||'.'||TRIM(TABLENAME)||' SELECT * FROM  '||TRIM(DATABASENAME)||'.'||TRIM(SUBSTR(TABLENAME, 1, 1))||'BK'||TRIM(SUBSTR(TABLENAME, 4,LENGTH(TABLENAME)))||';' (TITLE '') FROM  DBC.TABLESV
WHERE TABLEKIND ='T' AND TEMPORALPROPERTY <> 'N'
AND DATABASENAME IN (SELECT DISTINCT(PHYSICAL_DB) FROM SYS_DB_MAP)
ORDER BY CREATETIMESTAMP; 


.EXPORT RESET ;

.EXPORT REPORT FILE = DATA/GRANTALL.txt;

.SET WIDTH 64000;
 
.SET TITLEDASHES OFF;

.SET FOLDLINE OFF;

SELECT 'GRANT ALL  ON ' || TRIM(DATABASENAME) || '.' || TRIM(TABLENAME) ||  ' TO '||USER||';' (TITLE '') FROM DBC.TABLESV
WHERE DATABASENAME IN (SELECT DISTINCT(PHYSICAL_DB) FROM SYS_DB_MAP)
AND TABLEKIND = 'T';



.EXPORT RESET ;

.RUN FILE DATA/DROP_BKP.txt;

.RUN FILE DATA/RENAME_TAB.txt;

.RUN FILE DATA/DDL.txt

.RUN FILE DATA/INSERT_TAB.txt;

.RUN FILE DATA/GRANTALL.txt;

.RUN FILE DATA/DROP_BKP.txt;

DELETE FROM S_E2E_LOG ;


.QUIT
